create database Customer_seg;
use Customer_seg;

select * from customer;

---- Droping unknown column ----

Alter table customer drop column MyUnknownColumn;

--- 1.what is the total Revenue generated by male and Female ---

select Gender,sum(Purchase_Amount) as Revenue 
from customer 
group by gender ;

--- 2.which customers used a dicount ut still spent more than avg. purchase amunt ---

select Customer_Id , Purchase_Amount
from customer 
where Discount_Applied = 'Yes' and Purchase_Amount >=
( select avg (Purchase_Amount) from customer);

--- 3.which are the top 5 products with the highest avg. review rating --

SELECT Item_Purchased , round(avg(Review_Rating),2) as avg_Rating from customer 
group by Item_Purchased 
order by avg('Review_Rating') desc 
limit 5;


--- 4. Compare the avg. purcahse amount between standsrd and expess shipping 

select Shipping_Type ,round(avg(Purchase_Amount),2) as avg_amount 
from customer 
where Shipping_Type in ('Express','Standard')
group by Shipping_Type;



--- 5. do subscribed customer spend more? comapre avg. spend and total revenue betwwn subscrib and non sub ---


select Subscription_Status,
round(avg(Purchase_Amount),2) as avg_spend,
round(sum(Purchase_Amount),2) as total_spend 
from customer group by Subscription_Status
order by total_spend , avg_spend desc ;



--- 6. what are the top 3 purcharsed product within each category 

select 
Category,
Item_Purchased,
count(Customer_Id)  as total_cont,
row_number()
over(partition by Category order by count(Customer_Id) desc) as item_count
from customer
 group by Category , Item_Purchased;
 


--- 7.what is the revenue contribution of each age_group 

select Age_group,
sum(Purchase_Amount) as revenue 
from customer 
group by Age_group
order by sum(Purchase_Amount) desc;



---  8.Are customer who repeartyed buyers more than 5 purchase also like to sub 


select 
Subscription_Status, 
count('Customer_Id') as Repeated_customer 
from customer 
where Previous_Purchases > 5
group by Subscription_Status;








